<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Selatza.Learn</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Optimize>true</Optimize>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Selatza.Engine\Selatza.Engine.csproj" />
  </ItemGroup>
</Project>
