import type { DeckList } from '../engine/engine';
import { hiddenCard } from '../engine/redact';
import { registerCards } from '../engine/registry';
import './shared-choices';
import { blueCards } from './blue';
import { greenCards } from './green';
import { mixedCards } from './mixed';
import { neutralCards } from './neutral';
import { placeholderCards } from './placeholder';
import { purpleCards } from './purple';
import { redCards } from './red';
import { tripleCards } from './triple';
import { yellowCards } from './yellow';

export const allCardSets = [
  redCards,
  purpleCards,
  greenCards,
  blueCards,
  yellowCards,
  mixedCards,
  tripleCards,
  neutralCards,
];

registerCards([
  hiddenCard,
  ...placeholderCards,
  ...redCards,
  ...purpleCards,
  ...greenCards,
  ...blueCards,
  ...yellowCards,
  ...mixedCards,
  ...tripleCards,
  ...neutralCards,
]);

/** [card id, copies] pairs, expanded into a flat deck list. */
type Entry = [string, number];

function build(entries: Entry[]): string[] {
  const out: string[] = [];
  for (const [id, n] of entries) for (let i = 0; i < n; i++) out.push(id);
  return out;
}

export interface StarterDeck extends DeckList {
  key: string;
  blurb: string;
  /** Test decks exist to exercise one mechanic, not to be balanced. */
  test?: boolean;
}

/**
 * The decks a new player picks from. One per colour, each behind that colour's
 * own leader, and every one the same shape: a fixed set of cards at two copies
 * apiece. A deck built out of one-ofs hides its plan; this way the list reads at
 * a glance. Evolved by the training tournament, trimmed down, then played against
 * each other until no matchup was lopsided.
 */
export const starterDecks: StarterDeck[] = [
  {
    key: 'emberchoir',
    name: 'Archlife',
    blurb: 'Aggressive swarm of pepper summons empowered by increased effect damage',
    leaderId: 'ph-archlife',
    cards: build([
      ['p2-deathknight', 2],
      ['p3-Pod', 2],
      ['n3-IneptRuler', 2],
      ['p3-Looker', 2],
      ['p2-ash demon', 2],
      ['px-potion', 2],
      ['n3-AcolyteofGrinkle', 2],
      ['p3-helaks', 2],
      ['px-flower', 2],
      ['n3-GrinkleBeast', 2],
      ['nx-ColdBread', 2],
      ['n2-Smithee', 2],
      ['p2-pinelyte', 2],
      ['px-planetblast', 2],
      ['p3-stareater', 2],
      ['p1-moonkrag', 2],
      ['p3-Tryybus', 2],
      ['p2-livingfort', 2],
      ['n1-lizard', 2],
      ['n1-Wallguy', 2],
      ['px-treasure', 2],
      ['p2-dragon', 2],
      ['ph-archlife', 2],
      ['n3-NerveLite', 2],
    ]),
  },
  {
    key: 'longnoon',
    name: 'Aetus Vox',
    blurb: 'Solar control deck that musters powerful effects after building up additional mana throughout the game.',
    leaderId: 's3-aetusvox',
    cards: build([
      ['n3-IneptRuler', 2],
      ['s2-livingruin', 2],
      ['nx-RockThrow', 2],
      ['sx-aetalglob', 2],
      ['s2-admirer', 2],
      ['s2-druid', 2],
      ['s2-ragick', 2],
      ['n3-Seam', 2],
      ['s2-bubblemancer', 2],
      ['s2-sunwalker', 2],
      ['sx-inkybook', 2],
      ['n1-lizard', 2],
      ['n2-LowWizard', 2],
      ['n1-Wallguy', 2],
      ['s2-orangefarmer', 2],
      ['nx-Mousetrap', 2],
      ['n1-mammal', 2],
      ['s3-brokensun', 2],
      ['s1-livingboot', 2],
      ['s1-livingraincloud', 2],
      ['sx-musicalflow', 2],
      ['sx-flowerpower', 2],
      ['sx-aetuscollection', 2],
      ['sx-plusfifty', 2],
    ]),
  },
  {
    key: 'rustmire',
    name: 'Cyber Siren',
    blurb: 'Machine and traps that stall the game until Enthrall steals the enemies best cards',
    leaderId: 'r3-cybersiren',
    cards: build([
      ['rx-grab', 2],
      ['r3-strangestation', 2],
      ['rh-player1', 2],
      ['r1-slicebot', 2],
      ['r2-digital nomad', 2],
      ['n3-IneptRuler', 2],
      ['r3-chemicalmen', 2],
      ['n3-Seam', 2],
      ['rx-battery', 2],
      ['n1-Wallguy', 2],
      ['n2-SecretLetter', 2],
      ['rx-stundevice', 2],
      ['rx-connect', 2],
      ['r2-badglitch', 2],
      ['r2-securitybot', 2],
      ['rx-plugzap', 2],
      ['n3-Ivy', 2],
      ['n1-weirdBird', 2],
      ['rx-siphon', 2],
      ['r3-maliciouscode', 2],
      ['n1-mammal', 2],
      ['rx-videogame', 2],
      ['r2-hobbyist', 2],
      ['r3-hatemachine', 2],
    ]),
  },
  {
    key: 'deepcurrent',
    name: 'The Fish',
    blurb: 'Weak Fish that flood the board early, and an endgame about winning the war of attrition.',
    leaderId: 'fh-thefish',
    cards: build([
      ['n3-IneptRuler', 2],
      ['fx-catch', 2],
      ['fx-fishgoop', 2],
      ['fx-puddlewarp', 2],
      ['n1-Wallguy', 2],
      ['f2-fishamalgam', 2],
      ['n3-GrinkleBeast', 2],
      ['f3-serpant', 2],
      ['fx-rainstorm', 2],
      ['fx-snacklebox', 2],
      ['f1-whaleshark', 2],
      ['f1-seasnake', 2],
      ['f1-swordfish', 2],
      ['fx-fishideology', 2],
      ['f1-longfish', 2],
      ['nx-ColdBread', 2],
      ['fx-scooba', 2],
      ['n3-Seam', 2],
      ['f1-urchin', 2],
      ['f3-infiniteship', 2],
      ['fx-error', 2],
      ['fx-riptide', 2],
      ['f2-jellyking', 2],
      ['n2-LesserGrinkle', 2],
    ]),
  },
  {
    key: 'hollowvigil',
    name: 'Rain God',
    blurb: 'Oil Spirits that grind out the game while wounds add up damage across the enemy board.',
    leaderId: 'o3-raingod',
    cards: build([
      ['o2-slime', 2],
      ['n1-mammal', 2],
      ['n3-Seam', 2],
      ['o2-boneknown', 2],
      ['o3-fungal', 2],
      ['n3-AcolyteofGrinkle', 2],
      ['o3-thelake', 2],
      ['ox-mysterycabin', 2],
      ['n1-weirdBird', 2],
      ['n3-GrinkleBeast', 2],
      ['o3-bighatsalze', 2],
      ['n3-Relica', 2],
      ['ox-graft', 2],
      ['ox-campfire', 2],
      ['ox-lazyeye', 2],
      ['o1-skeleton', 2],
      ['o2-stabber', 2],
      ['o2-thecount', 2],
      ['o3-wickerman', 2],
      ['n2-SecretLetter', 2],
      ['n2-UngratefulBeast', 2],
      ['o1-jacklebox', 2],
      ['o2-evilflower', 2],
      ['o2-witch', 2],
    ]),
  },
];

/** Decks built to hammer one mechanic each. Not balanced, and not meant to be. */
export const testDecks: StarterDeck[] = [
  {
    key: 'tidewatch',
    name: 'Tidewatch Machine',
    blurb: 'Fish and Robot. Dual cards on a dual leader.',
    test: true,
    leaderId: 'm-bg-machineblue',
    cards: build([
      ['f1-basicfish', 2],
      ['f1-lilfish', 2],
      ['f1-longfish', 2],
      ['f1-octopi', 2],
      ['f1-seabunny', 2],
      ['f1-seahorse', 2],
      ['f1-seasnake', 2],
      ['f1-urchin', 2],
      ['f2-coralhead', 2],
      ['f2-fishwizard', 2],
      ['fx-catch', 2],
      ['fx-chumbucket', 1],
      ['fx-fishgoop', 2],
      ['m-bg-fishcode', 2],
      ['m-bg-greenorblue', 2],
      ['m-bg-hedronheart', 2],
      ['m-bg-robotfish', 2],
      ['r1-lapgrob', 2],
      ['r1-mouse', 2],
      ['r2-badglitch', 2],
      ['r2-bellobot', 2],
      ['r2-engineer', 2],
      ['rx-battery', 2],
      ['rx-plugzap', 2],
      ['rx-siphon', 2],
    ]),
  },
  {
    key: 'vanilla',
    name: 'Vanilla Dummies',
    blurb: 'No abilities anywhere. The baseline for combat maths and level-to-debt pacing.',
    leaderId: 'x-hero-dummy-warden',
    test: true,
    cards: build([
      ['x-f-bolt', 2],
      ['x-f-dummy-1', 2],
      ['x-f-dummy-2', 2],
      ['x-f-dummy-3', 2],
      ['x-o-bolt', 2],
      ['x-o-dummy-1', 2],
      ['x-o-dummy-2', 2],
      ['x-o-dummy-3', 2],
      ['x-p-bolt', 2],
      ['x-p-dummy-1', 2],
      ['x-p-dummy-2', 2],
      ['x-p-dummy-3', 2],
      ['x-r-bolt', 2],
      ['x-r-dummy-1', 2],
      ['x-r-dummy-2', 2],
      ['x-r-dummy-3', 2],
      ['x-s-bolt', 2],
      ['x-s-dummy-1', 2],
      ['x-s-dummy-2', 2],
      ['x-s-dummy-3', 2],
    ]),
  },
  {
    key: 'trap-lab',
    name: 'Trap Lab',
    blurb: 'Every trap in the game, so response windows open on almost every attack.',
    leaderId: 'x-hero-dummy-warden',
    test: true,
    cards: build([
      ['fx-scooba', 2],
      ['m-rb-sordidmark', 2],
      ['ox-lazyeye', 2],
      ['px-banner', 2],
      ['rx-stundevice', 2],
      ['sx-hollowring', 2],
      ['x-f-bolt', 2],
      ['x-f-dummy-1', 2],
      ['x-f-dummy-2', 2],
      ['x-f-dummy-3', 2],
      ['x-o-bolt', 2],
      ['x-o-dummy-1', 2],
      ['x-o-dummy-2', 2],
      ['x-o-dummy-3', 2],
      ['x-p-bolt', 2],
      ['x-p-dummy-1', 2],
      ['x-p-dummy-2', 2],
      ['x-p-dummy-3', 2],
      ['x-r-dummy-1', 2],
      ['x-r-dummy-2', 2],
      ['x-r-dummy-3', 2],
      ['x-s-dummy-1', 2],
      ['x-s-dummy-2', 2],
      ['x-s-dummy-3', 2],
    ]),
  },
  {
    key: 'flip-lab',
    name: 'Flip Lab',
    blurb: 'Nothing but cards with flip effects, so every point of damage triggers something.',
    leaderId: 'x-hero-dummy-warden',
    test: true,
    cards: build([
      ['f1-basicfish', 2],
      ['f1-lilfish', 2],
      ['f1-longfish', 2],
      ['f1-octopi', 2],
      ['f1-seabunny', 2],
      ['f1-seahorse', 2],
      ['f1-urchin', 2],
      ['o1-butterfly', 2],
      ['o1-ghost', 2],
      ['o1-ghostbeast', 2],
      ['o1-jacklebox', 2],
      ['o1-spider', 2],
      ['p1-beetle', 2],
      ['p1-bunny', 2],
      ['r1-chipcrunch', 2],
      ['r1-lapgrob', 2],
      ['r1-lightbolbe', 2],
      ['s1-fluterat', 2],
      ['s1-livingflowers', 2],
      ['s1-shrubbunny', 2],
      ['x-f-dummy-1', 2],
      ['x-o-dummy-1', 2],
      ['x-p-dummy-1', 2],
      ['x-r-dummy-1', 2],
    ]),
  },
  {
    key: 'aura-lab',
    name: 'Aura Lab',
    blurb: 'Stages and lords in two colors, to watch continuous effects stack up.',
    leaderId: 'x-hero-dummy-warden',
    test: true,
    cards: build([
      ['f2-coralhead', 2],
      ['fx-fishideology', 2],
      ['fx-rainstorm', 2],
      ['m-yb-themoon', 2],
      ['m-yg-pragmistlaw', 2],
      ['s1-livingtree', 2],
      ['s2-sunwalker', 2],
      ['s3-oldgod', 2],
      ['s3-yellowplanet', 2],
      ['sx-musicalflow', 2],
      ['sx-party', 2],
      ['x-f-bolt', 2],
      ['x-f-dummy-1', 2],
      ['x-f-dummy-2', 2],
      ['x-f-dummy-3', 2],
      ['x-o-dummy-1', 2],
      ['x-o-dummy-2', 2],
      ['x-p-dummy-1', 2],
      ['x-p-dummy-2', 2],
      ['x-r-dummy-1', 2],
      ['x-s-bolt', 2],
      ['x-s-dummy-1', 2],
      ['x-s-dummy-2', 2],
      ['x-s-dummy-3', 2],
    ]),
  },
];

/**
 * Decks the tournament built rather than a person. Every body that can stand
 * as a leader was handed to an agent, and the population rebuilt its decks over
 * nine hundred rounds; the best deck for each colour and colour pair is kept.
 * Regenerate with scripts/export-evolved.mjs after a fresh run.
 */
export const evolvedDecks: StarterDeck[] = [
  {
    key: 'evo-f-infiniteship',
    name: 'The Infinite Ship',
    blurb: 'Fish. Evolved: 25 level 3 bodies and 8 spells, leaning on Error and Fish Goop.',
    leaderId: 'f3-infiniteship',
    cards: build([
      ['f1-swordfish', 2],
      ['f1-whaleshark', 2],
      ['f2-fishamalgam', 2],
      ['f2-fishfolk', 2],
      ['f2-jellyking', 1],
      ['f2-scubadoba', 2],
      ['f3-abyssalwalker', 2],
      ['f3-crabcity', 2],
      ['f3-darkness', 1],
      ['f3-deepseaheart', 2],
      ['f3-eternalalbatross', 2],
      ['f3-infiniteship', 1],
      ['f3-serpant', 2],
      ['fh-thefish', 2],
      ['fx-error', 2],
      ['fx-fishgoop', 2],
      ['fx-puddlewarp', 2],
      ['fx-snacklebox', 2],
      ['n2-HonorableKnight', 1],
      ['n2-LowWizard', 2],
      ['n2-UngratefulBeast', 1],
      ['n3-AcolyteofGrinkle', 2],
      ['n3-GambleLord', 1],
      ['n3-GrinkleBeast', 2],
      ['n3-IneptRuler', 2],
      ['n3-NerveLite', 2],
      ['n3-Seam', 2],
    ]),
  },
  {
    key: 'evo-o-eyesnight',
    name: 'Eyes of Night',
    blurb: 'Oil. Evolved: 19 level 3 bodies and 4 spells, leaning on Black Candle and Field: Campfire.',
    leaderId: 'o3-eyesnight',
    cards: build([
      ['n1-Thing', 1],
      ['n2-LowWizard', 2],
      ['n3-AcolyteofGrinkle', 2],
      ['n3-IneptRuler', 2],
      ['n3-Ivy', 1],
      ['n3-NerveLite', 2],
      ['n3-Seam', 2],
      ['nx-HomeOnAHill', 1],
      ['nx-Mousetrap', 1],
      ['o1-ghostbeast', 1],
      ['o1-jacklebox', 1],
      ['o1-skeleton', 1],
      ['o2-boneknown', 2],
      ['o2-evilflower', 1],
      ['o2-necromancer', 1],
      ['o2-slime', 2],
      ['o2-stabber', 2],
      ['o2-thecount', 2],
      ['o2-witch', 2],
      ['o3-devourer', 2],
      ['o3-fungal', 2],
      ['o3-mothhorror', 2],
      ['o3-raingod', 2],
      ['o3-wickerman', 2],
      ['ox-blackcandle', 2],
      ['ox-campfire', 2],
      ['ox-corruptedritual', 1],
      ['ox-lazyeye', 1],
      ['ox-mysterycabin', 2],
      ['ox-wishingclaw', 1],
    ]),
  },
  {
    key: 'evo-p-slicer',
    name: 'Slicer',
    blurb: 'Pepper. Evolved: 18 level 3 bodies and 6 spells, leaning on Ember Flower and Ember Tonic.',
    leaderId: 'p3-Slicer',
    cards: build([
      ['n1-CorruptGrinkling', 2],
      ['n1-LittleBunny', 1],
      ['n1-Thing', 1],
      ['n1-mammal', 1],
      ['n2-HonorableKnight', 2],
      ['n2-LesserGrinkle', 1],
      ['n2-NobodysFriend', 1],
      ['n2-Smithee', 2],
      ['n3-AcolyteofGrinkle', 2],
      ['n3-IneptRuler', 2],
      ['n3-Ivy', 1],
      ['n3-PowerBird', 2],
      ['p1-bunny', 2],
      ['p1-devil', 2],
      ['p2-ash demon', 2],
      ['p2-deathknight', 2],
      ['p2-dragon', 2],
      ['p2-lazylord', 1],
      ['p2-wizard', 1],
      ['p3-Looker', 2],
      ['p3-Pod', 2],
      ['p3-heavenknows', 2],
      ['p3-helaks', 1],
      ['p3-stareater', 2],
      ['ph-archlife', 2],
      ['px-castle', 1],
      ['px-flower', 2],
      ['px-planetblast', 1],
      ['px-poisondagger', 1],
      ['px-potion', 2],
    ]),
  },
  {
    key: 'evo-r-strangestation',
    name: 'Strange Station',
    blurb: 'Robot. Evolved: 16 level 3 bodies and 8 spells, leaning on Trap: Mousetrap and Rock Throw.',
    leaderId: 'r3-strangestation',
    cards: build([
      ['n1-BeautifulBug', 2],
      ['n1-CorruptGrinkling', 1],
      ['n1-mammal', 1],
      ['n2-Sorter', 1],
      ['n3-AcolyteofGrinkle', 1],
      ['n3-FlyingCastle', 1],
      ['n3-GrinkleBeast', 2],
      ['n3-IneptRuler', 2],
      ['n3-Ivy', 1],
      ['n3-NerveLite', 2],
      ['n3-Seam', 2],
      ['nx-Mousetrap', 2],
      ['nx-RockThrow', 2],
      ['r1-automoton', 1],
      ['r1-chipcrunch', 2],
      ['r1-computerbug', 1],
      ['r1-lapgrob', 1],
      ['r1-mouse', 2],
      ['r1-slicebot', 2],
      ['r2-badglitch', 1],
      ['r2-securitybot', 2],
      ['r3-hatemachine', 2],
      ['r3-infinitemind', 1],
      ['r3-maliciouscode', 2],
      ['rx-connect', 1],
      ['rx-grab', 2],
      ['rx-npcgenerator', 2],
      ['rx-plugzap', 2],
      ['rx-stundevice', 2],
      ['rx-thedodecahedron', 2],
    ]),
  },
  {
    key: 'evo-s-aetusvox',
    name: 'Aetus Vox',
    blurb: 'Solar. Evolved: 19 level 3 bodies and 7 spells, leaning on Flower Power and Trap: Hollow Ring.',
    leaderId: 's3-aetusvox',
    cards: build([
      ['n1-CorruptGrinkling', 1],
      ['n2-Deedsigner', 1],
      ['n2-LowWizard', 1],
      ['n3-AcolyteofGrinkle', 1],
      ['n3-GrinkleBeast', 2],
      ['n3-IneptRuler', 2],
      ['n3-Seam', 2],
      ['nx-ColdBread', 1],
      ['nx-HomeOnAHill', 1],
      ['nx-RockThrow', 1],
      ['s1-starbird', 2],
      ['s1-starsprite', 2],
      ['s2-admirer', 2],
      ['s2-druid', 2],
      ['s2-happybard', 2],
      ['s2-livingruin', 2],
      ['s2-orangefarmer', 2],
      ['s2-ragick', 2],
      ['s3-aetusvox', 2],
      ['s3-brokensun', 2],
      ['s3-goldwild', 2],
      ['s3-maestro', 2],
      ['s3-smallgod', 2],
      ['s3-yellowplanet', 2],
      ['sx-aetalglob', 1],
      ['sx-flowerpower', 2],
      ['sx-hollowring', 2],
      ['sx-inkybook', 1],
      ['sx-plusfifty', 1],
    ]),
  },
  {
    key: 'evo-of-enigmastelf',
    name: 'Enigmastelf',
    blurb: 'Oil and Fish. Evolved: 28 level 3 bodies and 9 spells, leaning on Baited and Fish Goop.',
    leaderId: 'm-bp-enigmastelf',
    cards: build([
      ['f2-jellyking', 2],
      ['f3-abyssalwalker', 2],
      ['f3-darkness', 2],
      ['f3-riverdrinker', 2],
      ['f3-serpant', 2],
      ['fx-catch', 2],
      ['fx-fishgoop', 2],
      ['m-bp-orb', 2],
      ['m-bp-voidbug', 2],
      ['n1-Wallguy', 1],
      ['n2-Deedsigner', 1],
      ['n3-AcolyteofGrinkle', 2],
      ['n3-GambleLord', 1],
      ['n3-GrinkleBeast', 2],
      ['n3-IneptRuler', 2],
      ['n3-NerveLite', 2],
      ['n3-Seam', 2],
      ['nx-Mousetrap', 1],
      ['o2-boneknown', 2],
      ['o2-parkranger', 1],
      ['o2-witch', 1],
      ['o3-fungal', 2],
      ['o3-mothhorror', 2],
      ['o3-raingod', 2],
      ['o3-wickerman', 1],
      ['ox-blackcandle', 2],
      ['ox-mysterycabin', 2],
      ['ox-wishingclaw', 1],
    ]),
  },
  {
    key: 'evo-pf-sordidbeast',
    name: 'Sordid Beast',
    blurb: 'Pepper and Fish. Evolved: 21 level 3 bodies and 9 spells, leaning on Baited and Fish Goop.',
    leaderId: 'm-rb-sordidbeast',
    cards: build([
      ['f1-whaleshark', 1],
      ['f2-jellyking', 1],
      ['f3-abyssalwalker', 2],
      ['f3-darkness', 2],
      ['f3-eternalalbatross', 2],
      ['f3-serpant', 2],
      ['f3-sharkmeat', 1],
      ['fx-catch', 2],
      ['fx-fishgoop', 2],
      ['fx-fishify', 1],
      ['fx-snacklebox', 2],
      ['m-rb-xyliss', 1],
      ['n2-LowWizard', 2],
      ['n2-NobodysFriend', 2],
      ['n2-SecretLetter', 1],
      ['n2-Smithee', 2],
      ['n2-UngratefulBeast', 1],
      ['n3-AcolyteofGrinkle', 1],
      ['n3-IneptRuler', 2],
      ['n3-NerveLite', 1],
      ['p1-bunny', 1],
      ['p1-devil', 1],
      ['p2-evil squire', 2],
      ['p2-lazylord', 2],
      ['p3-Pod', 2],
      ['p3-Slicer', 1],
      ['p3-Tryybus', 1],
      ['p3-helaks', 1],
      ['p3-stareater', 2],
      ['px-banner', 1],
      ['px-castle', 1],
      ['px-flower', 2],
    ]),
  },
  {
    key: 'evo-rf-machineblue',
    name: 'Machine Blue',
    blurb: 'Robot and Fish. Evolved: 24 level 3 bodies and 10 spells, leaning on Fish Goop and Trap: Mousetrap.',
    leaderId: 'm-bg-machineblue',
    cards: build([
      ['f1-whaleshark', 2],
      ['f2-jellyking', 2],
      ['f3-abyssalwalker', 2],
      ['f3-darkness', 2],
      ['f3-serpant', 2],
      ['fx-fishgoop', 2],
      ['fx-scooba', 1],
      ['m-bg-machineblue', 2],
      ['n1-CorruptGrinkling', 1],
      ['n1-Wallguy', 1],
      ['n2-LowWizard', 1],
      ['n3-AcolyteofGrinkle', 2],
      ['n3-GrinkleBeast', 1],
      ['n3-IneptRuler', 2],
      ['n3-Seam', 2],
      ['nx-Mousetrap', 2],
      ['nx-RockThrow', 2],
      ['r2-badglitch', 1],
      ['r2-digital nomad', 2],
      ['r2-nommer', 1],
      ['r3-chemicalmen', 2],
      ['r3-hatemachine', 2],
      ['r3-infinitemind', 2],
      ['r3-maliciouscode', 1],
      ['r3-strangestation', 2],
      ['rx-battery', 2],
      ['rx-npcgenerator', 2],
      ['rx-plugzap', 2],
    ]),
  },
  {
    key: 'evo-fs-themoon',
    name: 'The Moon',
    blurb: 'Fish and Solar. Evolved: 27 level 3 bodies and 7 spells, leaning on Baited and Celebrate.',
    leaderId: 'm-yb-themoon',
    cards: build([
      ['f1-seasnake', 1],
      ['f1-whaleshark', 2],
      ['f2-fishamalgam', 1],
      ['f3-darkness', 2],
      ['f3-eternalalbatross', 2],
      ['f3-serpant', 2],
      ['fx-catch', 2],
      ['fx-error', 1],
      ['fx-puddlewarp', 1],
      ['m-yb-ambrosia', 2],
      ['m-yb-livingriver', 1],
      ['m-yb-themoon', 2],
      ['n2-Starfly', 1],
      ['n3-AcolyteofGrinkle', 2],
      ['n3-IneptRuler', 2],
      ['n3-NerveLite', 1],
      ['nx-RockThrow', 1],
      ['s1-starbird', 1],
      ['s2-druid', 1],
      ['s2-hiker', 2],
      ['s2-sunwalker', 2],
      ['s3-aetusvox', 2],
      ['s3-brokensun', 2],
      ['s3-maestro', 2],
      ['s3-smallgod', 2],
      ['s3-solusdetteri', 2],
      ['s3-yellowplanet', 2],
      ['sx-celebrate', 2],
      ['sx-hollowring', 2],
    ]),
  },
  {
    key: 'evo-po-theking',
    name: 'The King',
    blurb: 'Pepper and Oil. Evolved: 25 level 3 bodies and 3 spells, leaning on Bucket and Black Candle.',
    leaderId: 'm-rp-theking',
    cards: build([
      ['m-rp-falsehumanity', 2],
      ['m-rp-theking', 2],
      ['n2-LowWizard', 1],
      ['n2-Smithee', 2],
      ['n3-AcolyteofGrinkle', 2],
      ['n3-GrinkleBeast', 2],
      ['n3-IneptRuler', 2],
      ['n3-Ivy', 1],
      ['nx-Bucket', 1],
      ['o1-butterfly', 1],
      ['o1-jacklebox', 2],
      ['o2-boneknown', 2],
      ['o2-slime', 2],
      ['o3-fungal', 2],
      ['o3-mothhorror', 2],
      ['o3-raingod', 2],
      ['o3-wickerman', 2],
      ['ox-blackcandle', 1],
      ['ox-wishingclaw', 1],
      ['p1-beast', 1],
      ['p1-bunny', 2],
      ['p1-devil', 2],
      ['p2-ash demon', 2],
      ['p2-deathknight', 1],
      ['p3-Looker', 1],
      ['p3-classe', 2],
      ['p3-heavenknows', 2],
      ['p3-helemy', 1],
      ['p3-stareater', 1],
      ['ph-archlife', 1],
    ]),
  },
  {
    key: 'evo-or-cybergore',
    name: 'Cybergore',
    blurb: 'Oil and Robot. Evolved: 24 level 3 bodies and 9 spells, leaning on Rock Throw and Black Candle.',
    leaderId: 'm-pg-Cybergore',
    cards: build([
      ['m-pg-AncientVirus', 1],
      ['m-pg-Cybergore', 2],
      ['n1-LittleBunny', 2],
      ['n1-Wallguy', 1],
      ['n2-Starfly', 1],
      ['n3-AcolyteofGrinkle', 1],
      ['n3-IneptRuler', 2],
      ['n3-Relica', 2],
      ['nx-HomeOnAHill', 1],
      ['nx-RockThrow', 2],
      ['o1-jacklebox', 2],
      ['o1-owl', 2],
      ['o3-darksideofthemoon', 2],
      ['o3-fungal', 2],
      ['o3-mothhorror', 2],
      ['o3-raingod', 1],
      ['ox-blackcandle', 2],
      ['r1-chipcrunch', 2],
      ['r2-securitybot', 1],
      ['r3-chemicalmen', 2],
      ['r3-greenstar', 2],
      ['r3-hatemachine', 2],
      ['r3-infinitemind', 2],
      ['r3-strangestation', 2],
      ['rx-battery', 1],
      ['rx-grab', 2],
      ['rx-plugzap', 2],
      ['rx-thedodecahedron', 2],
    ]),
  },
  {
    key: 'evo-os-xalbriss',
    name: 'M-Xalbriss',
    blurb: 'Oil and Solar. Evolved: 27 level 3 bodies and 4 spells, leaning on Trap: Mousetrap and Aetal Glob.',
    leaderId: 'm-yp-m-xalbriss',
    cards: build([
      ['m-yp-m-xalbriss', 2],
      ['m-yp-parthultfanatic', 1],
      ['n2-Starfly', 1],
      ['n3-AcolyteofGrinkle', 1],
      ['n3-GrinkleBeast', 1],
      ['n3-IneptRuler', 2],
      ['n3-Relica', 1],
      ['n3-Seam', 2],
      ['nx-Mousetrap', 2],
      ['o2-boneknown', 2],
      ['o2-slime', 2],
      ['o2-stabber', 1],
      ['o3-darksideofthemoon', 2],
      ['o3-fungal', 2],
      ['o3-raingod', 2],
      ['o3-thelake', 2],
      ['ox-campfire', 1],
      ['s2-admirer', 2],
      ['s2-happybard', 1],
      ['s2-livingruin', 1],
      ['s2-orangefarmer', 2],
      ['s2-sunwalker', 2],
      ['s3-aetusvox', 2],
      ['s3-maestro', 2],
      ['s3-smallgod', 2],
      ['s3-solusdetteri', 2],
      ['s3-yellowplanet', 2],
      ['sx-aetalglob', 2],
      ['sx-flowerpower', 1],
    ]),
  },
  {
    key: 'evo-pr-obelisks',
    name: 'The Obelisks',
    blurb: 'Pepper and Robot. Evolved: 15 level 3 bodies and 12 spells, leaning on Recompiler and Ember Flower.',
    leaderId: 'm-rg-obelisks',
    cards: build([
      ['m-rg-recompiler', 2],
      ['n1-Wallguy', 1],
      ['n2-LesserGrinkle', 1],
      ['n2-UngratefulBeast', 1],
      ['n3-AcolyteofGrinkle', 2],
      ['n3-GrinkleBeast', 1],
      ['n3-IneptRuler', 1],
      ['n3-Ivy', 2],
      ['n3-NerveLite', 1],
      ['n3-PowerBird', 1],
      ['p2-ash demon', 2],
      ['p2-deathknight', 2],
      ['p2-lazylord', 2],
      ['p3-Pod', 2],
      ['p3-stareater', 1],
      ['px-flower', 2],
      ['r1-defender', 2],
      ['r2-digital nomad', 2],
      ['r2-nommer', 2],
      ['r2-securitybot', 1],
      ['r3-greenstar', 2],
      ['r3-strangestation', 2],
      ['rx-battery', 2],
      ['rx-connect', 2],
      ['rx-npcgenerator', 2],
      ['rx-plugzap', 2],
      ['rx-siphon', 2],
      ['rx-thedodecahedron', 1],
      ['rx-videogame', 2],
    ]),
  },
  {
    key: 'evo-ps-sasparsol',
    name: 'Saspar-Sol',
    blurb: 'Pepper and Solar. Evolved: 19 level 3 bodies and 5 spells, leaning on Ember Flower and Ember Tonic.',
    leaderId: 'm-yr-sasparsol',
    cards: build([
      ['m-yr-scarletbloom', 2],
      ['n1-BucketGuardian', 1],
      ['n1-weirdBird', 1],
      ['n2-LesserGrinkle', 1],
      ['n2-Smithee', 2],
      ['n2-UngratefulBeast', 1],
      ['n3-IneptRuler', 2],
      ['n3-NerveLite', 1],
      ['nx-HomeOnAHill', 1],
      ['p1-bunny', 2],
      ['p1-devil', 1],
      ['p2-ash demon', 2],
      ['p2-dragon', 2],
      ['p3-Looker', 2],
      ['p3-Tryybus', 2],
      ['p3-heavenknows', 2],
      ['p3-helaks', 2],
      ['px-banner', 1],
      ['px-flower', 2],
      ['px-potion', 2],
      ['px-treasure', 1],
      ['s1-fluterat', 2],
      ['s1-starbird', 1],
      ['s2-happybard', 1],
      ['s2-livingruin', 1],
      ['s2-ragick', 2],
      ['s3-brokensun', 2],
      ['s3-maestro', 2],
      ['s3-smallgod', 2],
      ['s3-solusdetteri', 2],
    ]),
  },
  {
    key: 'evo-rs-pilgrim',
    name: 'Pilgrim',
    blurb: 'Robot and Solar. Evolved: 23 level 3 bodies and 6 spells, leaning on Field: Home on a Hill and Grab.',
    leaderId: 'm-yg-pilgrim',
    cards: build([
      ['n1-weirdBird', 1],
      ['n2-Smithee', 2],
      ['n2-UngratefulBeast', 1],
      ['n3-GrinkleBeast', 2],
      ['n3-IneptRuler', 2],
      ['n3-Ivy', 1],
      ['n3-NerveLite', 2],
      ['n3-Seam', 1],
      ['nx-HomeOnAHill', 2],
      ['r3-hatemachine', 2],
      ['r3-infinitemind', 2],
      ['r3-strangestation', 2],
      ['rx-grab', 2],
      ['rx-plugzap', 2],
      ['rx-stundevice', 2],
      ['rx-videogame', 2],
      ['s1-livingrock', 1],
      ['s2-admirer', 2],
      ['s2-hiker', 2],
      ['s2-livingruin', 1],
      ['s2-ragick', 1],
      ['s2-sunwalker', 2],
      ['s3-aetusvox', 2],
      ['s3-brokensun', 1],
      ['s3-maestro', 2],
      ['s3-smallgod', 2],
      ['s3-solusdetteri', 2],
      ['sx-hollowring', 2],
    ]),
  },
];

export const allDecks: StarterDeck[] = [...starterDecks, ...testDecks];

/** Everything selectable, including the evolved decks. */
export const everyDeck: StarterDeck[] = [...allDecks, ...evolvedDecks];

export function deckByKey(key: string): StarterDeck {
  const d = allDecks.find((x) => x.key === key);
  if (!d) throw new Error(`unknown deck: ${key}`);
  return d;
}

export {
  blueCards,
  greenCards,
  mixedCards,
  placeholderCards,
  purpleCards,
  redCards,
  tripleCards,
  yellowCards,
};
